"""initial migration

Revision ID: cbefb21be93d
Revises: 62404b481dd2
Create Date: 2016-07-21 15:43:24.005000

"""

# revision identifiers, used by Alembic.
revision = 'cbefb21be93d'
down_revision = '62404b481dd2'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirmed')
    ### end Alembic commands ###
