"""initial migration

Revision ID: e246a25baaed
Revises: e0a8ad1a90ae
Create Date: 2016-07-25 15:52:29.633000

"""

# revision identifiers, used by Alembic.
revision = 'e246a25baaed'
down_revision = 'e0a8ad1a90ae'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_hash', sa.String(length=32), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_hash')
    ### end Alembic commands ###
